repos:
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
          # - flake8-bugbear
          # - flake8-comprehensions
          - flake8-simplify